### PR TITLE
refactor(service): avoid using expect in tx hook

### PR DESCRIPTION
**Pull request by KaoImin**
**What type of PR is this?**
refactor

**What this PR does / why we need it**:
Avoid using expect in tx hook. Use the cancel method of `ServiceContext` to return error.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by yejiayu** [comment]
require unit test

**Review by LycrusHamster — APPROVED** [review]

**Pull request merged**
